# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0058ed060752fac2fa825267e28c0216b3cc6fe64720fbe0976c28e0b896b96a67d86570eb4144fa157e3b75c4a4359d0ee70e9416d616eae60d9ee4c31a6785
  paypal_host: https://www.sandbox.paypal.com
  app_host: <%= ENV["NGROK"] %>
test:
  secret_key_base: 9f5439210fc7a1ca902a14eef20c2b3884dc07de534f3ba977475e59895706979ab114a4e35dcc6d250e5ae13023dc5a65af60bb49da3774818d334c7308cb22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  paypal_host: https://www.paypal.com
  app_host: https://lideploy.com/
